<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Simulation Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Simulation Challenge</h1>
<p class="subtitle lead">Starter Template with To-Dos</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="simulation-challenge---starter-template" class="level1">
<h1>🎲 Simulation Challenge - Starter Template</h1>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>📋 What You Need To Do
</div>
</div>
<div class="callout-body-container callout-body">
<ul class="task-list">
<li><label><input type="checkbox">Fork and create repo <code>simulationChallenge</code> in your GitHub</label></li>
<li><label><input type="checkbox">Clone locally and open in Cursor</label></li>
<li><label><input type="checkbox">Write your analysis in this <code>index.qmd</code></label></li>
<li><label><input type="checkbox">Render to HTML (<code>quarto render</code> or Render button)</label></li>
<li><label><input type="checkbox">Push HTML to your repo and enable GitHub Pages</label></li>
<li><label><input type="checkbox">Share your site: <code>https://[your-username].github.io/simulationChallenge/</code></label></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>⚠️ AI Partnership Required
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use Cursor AI for speed, but ensure you understand and can explain the results in your own words. Verify cursor’s calculations as investment simulation is tricky.</p>
</div>
</div>
<section id="the-investment-game-brief" class="level2">
<h2 class="anchored" data-anchor-id="the-investment-game-brief">The Investment Game (Brief)</h2>
<p>You have the opportunity to buy-in to this game next week with $30,000. Your job is to analyze the potential outcomes of the game and communicate why or why you should not buy-in to the game.</p>
<p>After each coin flip:</p>
<ul>
<li>Heads: increase your account balance by 50%</li>
<li>Tails: decrease your account balance by 40%</li>
</ul>
<p>You flip the coin 35 times. Your mission is to analyze outcomes and communicate insights clearly.</p>
<section id="generative-dag-model-from-the-source-challenge" class="level3">
<h3 class="anchored" data-anchor-id="generative-dag-model-from-the-source-challenge">Generative DAG Model (from the source challenge)</h3>
<p>The following DAFT diagram shows the generative structure of the investment game over time.</p>
<div id="cell-fig-investment-dag" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-investment-dag" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-investment-dag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-investment-dag-output-1.png" width="649" height="220" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-investment-dag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Generative DAG model for the investment game showing how wealth evolves over time through coin flips
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="analysis-tasks-fill-these-in" class="level2">
<h2 class="anchored" data-anchor-id="analysis-tasks-fill-these-in">Analysis Tasks (Fill These In)</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Grading Scope
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Sections 1–4: required and can earn up to 90% of the grade.</li>
<li>Sections 5–6: optional; strong, well-supported work here can bring your score up to 100%.</li>
</ul>
</div>
</div>
<section id="expected-value-after-1-flip" class="level3">
<h3 class="anchored" data-anchor-id="expected-value-after-1-flip">1) Expected Value After 1 Flip</h3>
<p>What is the gain in expected value as a percentage of your buy-in? Does this simple analysis suggest you should buy-in to the game?</p>
<div id="q1-expected-value-py" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>Expected value after one flip: $31,500.00
Gain in expected value: $1,500.00 (5.00%)

The expected value of your account balance after one flip is $31,500.00.
This is less than $30,000, so you should not buy-in to the game based on expected value alone.</code></pre>
</div>
</div>
</section>
<section id="single-simulation-over-time-narrative-plot" class="level3">
<h3 class="anchored" data-anchor-id="single-simulation-over-time-narrative-plot">2) Single Simulation Over Time (Narrative + Plot)</h3>
<p>Following visualize and narrative explains what happens to account balance over the course of one run.</p>
<div id="cell-q2-single-sim-py" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>Starting balance: $30,000.00
Final balance after 35 coin flips: $293,153.58
Change: $263,153.58 (877.18%)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/var/folders/_m/fd3rypln675c08nyp691yvb00000gn/T/ipykernel_17591/207306678.py:99: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  legend = ax.legend(loc='upper left', framealpha=0.95, fontsize=10.5,</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="q2-single-sim-py" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/q2-single-sim-py-output-3.png" width="753" height="467" class="figure-img"></p>
<figcaption>Single simulation path of account balance</figcaption>
</figure>
</div>
</div>
</div>
<p>Starting with $30,000.00, the simulation ran through 35 coin flips. Out of 35 flips, 22 resulted in gains (heads: +50%) and 13 resulted in losses (tails: -40%).</p>
<p><strong>Key Moments:</strong> - Maximum balance: $307,546.88 reached at coin flip 8 - Minimum balance: $30,000.00 reached at coin flip 0 - Final balance: $293,153.58 after 35 coin flips</p>
<p><strong>✅ OUTCOME ASSESSMENT: I am HAPPY with this outcome. Its not profitable all time and its risky investment </strong></p>
<p>The investment grew from $30,000.00 to $293,153.58, representing a 877.18% return. This is a 877.18% profit on the initial investment. Despite the volatility shown in the graph (with gains and losses throughout), the final result shows a positive return, which meets the basic goal of earning more than what was initially invested.</p>
<p>The simulation demonstrates the high volatility inherent in this investment game, with balance fluctuating dramatically between coin flips. The color-coded line shows alternating periods of gains (green) and losses (red), illustrating the risky nature of this strategy.</p>
</section>
<section id="simulations-distribution-of-final-balances" class="level3">
<h3 class="anchored" data-anchor-id="simulations-distribution-of-final-balances">3) 100 Simulations: Distribution of Final Balances</h3>
<p>Visually and narratively describe the distribution of your account balance after running the 100 simulations. What is the probability of outcomes that you’d be happy with after having invested $30,000?</p>
<div id="q3-dist-100-py" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/q3-dist-100-py-output-1.png" id="q3-dist-100-py-1" width="748" height="465" class="figure-img"></p>
</figure>
</div>
</div>
<div id="q3-dist-100-py-2" class="cell-output cell-output-display cell-output-markdown">
<p>The following are the distribution analysis of the 100 simulations:</p>
<p><strong>DISTRIBUTION ANALYSIS</strong></p>
<p>Simulation Parameters:</p>
<ul>
<li>Initial investment: $30,000</li>
<li>Number of coin flips: 35</li>
<li>Number of simulations: 100</li>
</ul>
<p><strong>Distribution Statistics:</strong></p>
<ul>
<li>Mean final balance: $392,420.53</li>
<li>Median final balance: $5,253.31</li>
<li>Standard deviation: $1,722,044.59</li>
<li>Minimum final balance: $4.92</li>
<li>Maximum final balance: $11,451,311.90</li>
</ul>
<p><strong>Probability of favorable outcomes:</strong></p>
<ul>
<li>P(final balance &gt; $30,000): 27.0% (27/100 simulations)</li>
<li>P(final balance ≥ $60,000): 18.0% (18/100 simulations)</li>
<li>P(final balance ≥ $30,000): 27.0% (break-even or better)</li>
</ul>
</div>
<div id="q3-dist-100-py-3" class="cell-output cell-output-display cell-output-markdown">
<p>After running 100 simulations of the investment game over 35 coin flips:</p>
<p><strong>1. DISTRIBUTION CHARACTERISTICS:</strong></p>
<ul>
<li>The distribution is highly skewed with a long right tail</li>
<li>Mean balance ($392,420.53) is higher than median ($5,253.31)</li>
<li>This indicates extreme outcomes: some simulations result in very high balances, while others result in significant losses</li>
<li>The wide range ($4.92 to $11,451,311.90) shows high variability</li>
</ul>
<p><strong>2. PROBABILITY OF HAPPY OUTCOMES:</strong></p>
<ul>
<li>After investing $30,000, the probability of ending with <strong>MORE</strong> than your initial investment is 27.0%</li>
<li>This means in 27 out of 100 simulations, you would be profitable</li>
<li>The probability of at least DOUBLING your money is 18.0%</li>
</ul>
<p><strong>3. RISK ASSESSMENT:</strong></p>
<ul>
<li>Less than half of simulations result in profit - this is a HIGH RISK investment</li>
<li>The high standard deviation ($1,722,044.59) indicates significant uncertainty</li>
<li>You could lose as much as $29,995.08 or gain as much as $11,421,311.90</li>
</ul>
<p><strong>4. CONCLUSION:</strong> If you define ‘happy outcomes’ as finishing with more than your $30,000 investment, the probability is 27.0% However, the extreme variability means outcomes are highly unpredictable</p>
</div>
</div>
</section>
<section id="probability-balance-30000-after-35-coin-flips-original-game" class="level3">
<h3 class="anchored" data-anchor-id="probability-balance-30000-after-35-coin-flips-original-game">4) Probability Balance &gt; $30,000 After 35 Coin Flips (Original Game)</h3>
<p>Report the probability estimate and interpret its practical meaning.</p>
<div id="q4-prob-original-py" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code>Number of successful simulations (Final Balance &gt; $30,000): 27.00
Total number of simulations: 100
The probability of ending with more than $30,000 after 35 coin flips is 0.270
This means that in 27 out of 100 simulations, you would be profitable.</code></pre>
</div>
</div>
</section>
<section id="modified-strategy-bet-exactly-50-each-round" class="level3">
<h3 class="anchored" data-anchor-id="modified-strategy-bet-exactly-50-each-round">5) Modified Strategy (Bet Exactly 50% Each Round)</h3>
<p>Instead of having the full balance at risk with each coin flip, assume only 50% of balance is gambled each round. Compare this to the original game. Which is riskier? Which has better upside?</p>
<div id="q5-modified-50pct-py" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="q5-modified-50pct-py-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/q5-modified-50pct-py-output-1.png" width="752" height="465" class="figure-img"></p>
<figcaption>Comparison of original and modified strategy distributions (bet 50% each round)</figcaption>
</figure>
</div>
</div>
<div id="q5-modified-50pct-py-2" class="cell-output cell-output-display cell-output-markdown">
<section id="original-vs-modified-strategy-50-at-risk" class="level3">
<h3 class="anchored" data-anchor-id="original-vs-modified-strategy-50-at-risk"><strong>Original vs Modified Strategy (50% at Risk)</strong></h3>
<section id="original-strategy-full-balance-at-risk" class="level4">
<h4 class="anchored" data-anchor-id="original-strategy-full-balance-at-risk">Original Strategy (Full Balance at Risk)</h4>
<ul>
<li>Mean final balance: $41,422.34</li>
<li>Median final balance: $2,101.32</li>
<li>Standard deviation: $196,035.97</li>
<li>Minimum: $4.92</li>
<li>Maximum: $1,832,209.90</li>
<li>P(final &gt; $30,000): 18.00%</li>
<li>Profitable simulations: 18/100</li>
</ul>
</section>
<section id="modified-strategy-50-of-balance-at-risk" class="level4">
<h4 class="anchored" data-anchor-id="modified-strategy-50-of-balance-at-risk">Modified Strategy (50% of Balance at Risk)</h4>
<ul>
<li>Mean final balance: $57,339.82</li>
<li>Median final balance: $24,000.00</li>
<li>Standard deviation: $85,218.37</li>
<li>Minimum: $675.54</li>
<li>Maximum: $545,696.82</li>
<li>P(final &gt; $30,000): 48.00%</li>
<li>Profitable simulations: 48/100</li>
</ul>
</section>
<section id="comparison" class="level4">
<h4 class="anchored" data-anchor-id="comparison"><strong>Comparison</strong></h4>
<ul>
<li>Mean difference: $15,917.48</li>
<li>Std dev ratio (mod/orig): 0.43</li>
<li>Max difference: $-1,286,513.08</li>
<li>Min difference: $670.62</li>
<li>Probability gain diff: 30.00%</li>
</ul>
</section>
<section id="interpretation-which-is-riskier-which-has-better-upside" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-which-is-riskier-which-has-better-upside"><strong>Interpretation: Which is Riskier? Which has Better Upside?</strong></h4>
<p><strong>The Original Strategy (Full Balance at Risk) has:</strong></p>
<ul>
<li><p>The Original strategy is RISKIER (std dev: $196,035.97 vs $85,218.37)</p></li>
<li><p>Higher volatility means more uncertainty</p></li>
<li><p>The Original strategy has BETTER UPSIDE (max: $1,832,209.90 vs $545,696.82)</p></li>
<li><p>Can achieve much higher maximum returns</p></li>
</ul>
</section>
</section>
</div>
<div id="q5-modified-50pct-py-3" class="cell-output cell-output-display cell-output-markdown">
<p><strong>The Modified Strategy (50% at risk) has:</strong></p>
<ul>
<li><p>Lower risk per round (only 50% of balance exposed to coin flip)</p></li>
<li><p>More conservative approach (50% always kept safe)</p></li>
<li><p>Lower maximum potential but also lower minimum loss</p></li>
<li><p>Reduced volatility compared to full-risk strategy</p></li>
</ul>
</div>
</div>
<section id="interpretation-of-the-distributions" class="level4">
<h4 class="anchored" data-anchor-id="interpretation-of-the-distributions">Interpretation of the distributions</h4>
</section>
<section id="what-the-figure-shows" class="level4">
<h4 class="anchored" data-anchor-id="what-the-figure-shows"><strong>What the figure shows</strong></h4>
<ul>
<li><p>Full-risk outcomes sprawl from $5 to $1,832,210; the long right tail raises the mean ($41,422) well above the median ($2,101).</p></li>
<li><p>The 50%-at-risk strategy compresses the range ($676 to $545,697), nudging the mean ($57,340) and median ($24,000) much closer together.</p></li>
<li><p>Only 18.0% of full-risk simulations finish above $30,000, versus 48.0% when half the balance is protected each flip.</p></li>
<li><p>The histogram’s overlapping bars make the trade-off clear: the original game delivers rare but massive wins, while the modified plan clusters in a narrower, more predictable band.</p></li>
</ul>
</section>
<section id="bottom-line" class="level4">
<h4 class="anchored" data-anchor-id="bottom-line"><strong>Bottom line</strong></h4>
<p>The chart confirms that cutting risk in half sacrifices extreme upside but dramatically improves the odds of walking away with more than the initial $30,000.</p>
</section>
</section>
<section id="briefly-explain-your-findings-from-the-previous-step-in-light-of-a-concept-known-as-the-kelly-criterion" class="level3">
<h3 class="anchored" data-anchor-id="briefly-explain-your-findings-from-the-previous-step-in-light-of-a-concept-known-as-the-kelly-criterion">6) Briefly Explain Your Findings From The Previous Step in Light of A Concept Known as the “Kelly Criterion”</h3>
</section>
</section>
<section id="kelly-criterion-summary" class="level2">
<h2 class="anchored" data-anchor-id="kelly-criterion-summary">Kelly Criterion Summary</h2>
<div id="q6-kelly-criterion" class="cell" data-execution_count="10">
<p><strong>Kelly Criterion Diagnostics</strong> - Kelly-optimal fraction to stake each flip: 25.0% - Expected log-growth at the Kelly fraction: 0.0062 per flip - Expected log-growth when staking 100% (original game): -0.0527 per flip - Expected log-growth when staking 50% (modified strategy): 0.0000 per flip</p>
</div>
<p>The Kelly Criterion is a bankroll-management rule that maximizes long-run wealth by choosing the bet fraction that maximizes expected log returns. In this coin-flip game, the optimal Kelly fraction is about 25.0%, so a Kelly bettor would stake roughly one-third of their bankroll each flip. Risking the entire balance (the original strategy) pushes the log-growth rate negative (-0.0527 per flip), which matches the histogram evidence of many wipeouts. Halving the stake to 50% raises the log-growth rate to 0.0000 per flip, moving closer to the Kelly-optimal path while still allowing meaningful upside. Practitioners often bet below the strict Kelly level to guard against streaks and model error; the modified strategy mirrors that prudence by always sheltering half of the account.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>